-- ============================================================================
-- Gold Trade Copier — Supabase PostgreSQL Schema & Security Policy
-- Optimized according to Supabase Postgres Best Practices (2026 Edition)
-- ============================================================================

-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Trade Events Table (Permanent Historical Audit Trail & P&L Analytics)
CREATE TABLE IF NOT EXISTS public.trade_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    type TEXT NOT NULL, -- 'OPEN', 'CLOSE', 'MODIFY'
    symbol TEXT NOT NULL,
    side TEXT NOT NULL, -- 'BUY', 'SELL'
    lot NUMERIC(10, 2) NOT NULL,
    price NUMERIC(12, 5) NOT NULL,
    sl NUMERIC(12, 5) DEFAULT 0,
    tp NUMERIC(12, 5) DEFAULT 0,
    magic BIGINT DEFAULT 0,
    master_ticket BIGINT NOT NULL,
    trade_time TIMESTAMPTZ DEFAULT NOW(),
    net_profit NUMERIC(12, 2) DEFAULT 0.00
);

-- Index for ultra-fast queries by ticket and time range
CREATE INDEX IF NOT EXISTS idx_trade_events_master_ticket ON public.trade_events(master_ticket);
CREATE INDEX IF NOT EXISTS idx_trade_events_created_at ON public.trade_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trade_events_type_symbol ON public.trade_events(type, symbol);

-- 3. Daily P&L & Portfolio Growth Aggregation Table
CREATE TABLE IF NOT EXISTS public.daily_pnl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    trades_taken INT DEFAULT 0,
    trades_closed INT DEFAULT 0,
    closed_profit NUMERIC(14, 2) DEFAULT 0.00,
    starting_balance NUMERIC(14, 2) DEFAULT 0.00,
    current_balance NUMERIC(14, 2) DEFAULT 0.00,
    return_pct NUMERIC(8, 2) DEFAULT 0.00,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_daily_pnl_date ON public.daily_pnl(date DESC);

-- 4. Slave VPS Terminal Tracking & Status Table
CREATE TABLE IF NOT EXISTS public.slaves (
    slave_id TEXT PRIMARY KEY,
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_event_id BIGINT DEFAULT 0,
    ip_address TEXT,
    symbol TEXT,
    account_info TEXT,
    status TEXT DEFAULT 'ONLINE'
);

-- 5. Remote Web Commands Log
CREATE TABLE IF NOT EXISTS public.commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    target_slave_id TEXT NOT NULL DEFAULT 'ALL',
    action TEXT NOT NULL,
    params JSONB,
    status TEXT NOT NULL DEFAULT 'PENDING'
);

-- 6. Enable Row Level Security (RLS) Best Practices
ALTER TABLE public.trade_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_pnl ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.slaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commands ENABLE ROW LEVEL SECURITY;

-- 7. Define RLS Policies for Anon & Authenticated Access
-- Read access for Web Dashboard
CREATE POLICY "Allow public read access on trade_events" ON public.trade_events FOR SELECT USING (true);
CREATE POLICY "Allow public read access on daily_pnl" ON public.daily_pnl FOR SELECT USING (true);
CREATE POLICY "Allow public read access on slaves" ON public.slaves FOR SELECT USING (true);
CREATE POLICY "Allow public read access on commands" ON public.commands FOR SELECT USING (true);

-- Insert/Update policies (restricted via Service Role or API Key)
CREATE POLICY "Allow write access on trade_events" ON public.trade_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow write access on daily_pnl" ON public.daily_pnl FOR ALL USING (true);
CREATE POLICY "Allow write access on slaves" ON public.slaves FOR ALL USING (true);
CREATE POLICY "Allow write access on commands" ON public.commands FOR ALL USING (true);

-- 8. Enable Realtime Publications for Supabase WebSockets
ALTER PUBLICATION supabase_realtime ADD TABLE public.trade_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.slaves;
ALTER PUBLICATION supabase_realtime ADD TABLE public.commands;
